name: Render documents

on:
  workflow_dispatch:
  push:
    paths:
      - "markdown/**.qmd"
  workflow_run:
    workflows: [Build csv and SQLite db]
    types:
      - completed

jobs:
  render-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - run: |-
        quarto --version 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: pip
    - name: Install python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Render documents
      run: |-
        quarto render markdown/ --to html
    - name: Commit and push if it changed 
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        echo '### Changed files' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        git show --name-only --format=tformat: >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        git pull --rebase
        git push
